apiVersion: batch/v1
kind: Job
metadata:
  name: mockapi-test-job
spec:
  backoffLimit: 0             # fail immediately if test fails
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: mockapi-tests
          image: mockapi-tests:latest
          imagePullPolicy: Never  # use local image loaded into kind
          command: ["bash", "ci/run_tests.sh"]
          env:
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: mockapi-env
                  key: BASE_URL
            - name: TOKEN
              valueFrom:
                configMapKeyRef:
                  name: mockapi-env
                  key: API_TOKEN
